llm:
  huggingface: google/gemma-2b-it
  bit_4: True
  temperature: 0.8
  context_window: 8192
  max_new_tokens: 2048
  device: auto

embedding:
  huggingface: sentence-transformers/all-mpnet-base-v2

chunk_size: 1024